name: first_pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello commit happened successfully!"
      - name: step2
        run: echo "This is second step!"
      - name: step3
        run: |
          echo "Hello from step 3"
          hostname
          pwd
          id
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello from job2 tests 1"
      - name: step2
        run: |
          echo "Step 2"
          sleep 10
      - name: step3
        run: |
          echo "Step 3"
          hostname
          id
          pwd
    needs: build
  test2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step1
        run: echo "Hello from job2 tests 1"
      - name: step2
        run: |
          echo "Step 2"
          sleep 10
      - name: step3
        run: |
          echo "Step 3"
          hostname
          id
          pwd
  deploy:
    runs-on: ubuntu-latest
    needs: [test, test2]
    steps:
      - name: step1
        run: echo "Hello from job2 tests 1"
      - name: step2
        run: |
          echo "Step 2"
          sleep 10
      - name: step3
        run: |
          echo "Step 3"
          hostname
          id
          pwd
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{always()}}
    steps:
      - name: step1
        run: echo "Notify pipeline"
      - name: step2
        run: |
          echo "Step 2"
          sleep 10
      - name: step3
        run: |
          echo "Step 3"
          hostname
          id
          pwd
          


             
    
        
