name: first_pipeline
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, commit happened successfully!"
      - name: step2
        run: echo "This is second step!"
      - name: step3
        run: |
          echo "Hello from step 3"
          hostname
          pwd
          id
        
