name: first_pipeline
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, commit happened successfully!"
      - name: step2
        run: echo "This is second step!"
      - name: step3
        run: |
          echo "Hello from step 3"
          hostname
          pwd
          id
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, in job 2commit happened successfully!"
      - name: step2
        run: echo "This is secind step in Job 2"
      - name: step3
        run: |
          echo "Hellp from step 3 in job 2"
          hostname
          pwd
          id
  
        
