name: second_pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - devOpsTrainingYashpal
  workflow_dispatch:
jobs:
  job1:
    runs-on: unbuntu-latest
    steps:
      - name: step1
        run: echo "Commit happened successfully"
      - name: step2
        run: |
          echo "step 2"
          sleep 30
      - name: step3
        run: |
          echo "Hello from step 3"
          hostname
          pwd
          sleep 30
          id
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hellp from job 2 step 1"
      - name: step2
        run: |
          echo "job2 step2"
          sleep 30
      - name: step3
        run: |
          echo "hello from job 2 step 3"
          sleep 20
          hostname
          pwd
          id
        
          
        
        
